### ISSUE TITLE
why are fx3_flagb_in and fx3_flagd_in unused?

### ISSUE THREAD

**Issue by AlessandroAU** [aprgl/fx3#3]
I've synthesized your vhd code. It appears that flagb and flagd are not read in the FSM.

How does it know when to stop reading/writing to the buffers on the fx3 without these two flags?

**Comment by aprgl** [comment]
I initially removed the watermark flags because they were causing an issue reading a transaction less than the watermark. I didn't use the _flag_d_ signal for the read path (fx3->fpga) and instead delayed _flag_c_ and _fx3_data_inout_ by two cycles in the _deal_with_delayed_flag_c_ routine.

Now that I saw your comment though I realize on the write side there's a chance for data loss if the fx3 buffer fills during a transfer due to the _flag_a_ three cycle latency.

**Comment by AlessandroAU** [comment]
Ah ok,

for the fpga-> fx3 path wouldn't it be possible to set the watermark to bufflen - 3? to account for the 3 clock delay? This way the FPGA can stop writing just in time?

**Comment by aprgl** [comment]
Yea, exactly. I've got the code changed to monitor flag_b in the write routine, just testing it on hardware before I push it up. Also adding a check to the testbench to catch this failure mode.
